//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordc_bah1
    {
        public string site { get; set; }
        public string ord_nbr { get; set; }
        public Nullable<System.DateTime> ord_date { get; set; }
        public string ord_class { get; set; }
        public string cus_id { get; set; }
        public string dept_no { get; set; }
        public string item_no { get; set; }
        public string item_name { get; set; }
        public string cus_item_no { get; set; }
        public string item_statistic { get; set; }
        public string item_type { get; set; }
        public string salesman { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> ord_qty { get; set; }
        public Nullable<decimal> manual_qty { get; set; }
        public string ord_unit { get; set; }
        public Nullable<decimal> aux_qty { get; set; }
        public string aux_unit { get; set; }
        public string season_y { get; set; }
        public string season { get; set; }
        public Nullable<System.DateTime> plan_fin_date { get; set; }
        public string vendor_id { get; set; }
        public string sam_nbr { get; set; }
        public string sam_times { get; set; }
        public string expand_yn { get; set; }
        public string agents { get; set; }
        public Nullable<decimal> estimate_ie { get; set; }
        public Nullable<decimal> actual_ie { get; set; }
        public Nullable<decimal> approved_ie { get; set; }
        public string trademark { get; set; }
        public string brand { get; set; }
        public string ingredients { get; set; }
        public Nullable<decimal> adv_amt { get; set; }
        public string bah_status { get; set; }
        public string crp_yn { get; set; }
        public string close_reason { get; set; }
        public string close_rmk { get; set; }
        public string filter_dept { get; set; }
        public string filter_creator { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<decimal> est_gross_pcs { get; set; }
        public Nullable<decimal> real_gross_pcs { get; set; }
        public Nullable<decimal> expense_dozen { get; set; }
        public Nullable<decimal> main_cost { get; set; }
        public Nullable<decimal> sub_cost { get; set; }
        public Nullable<decimal> extra_expense { get; set; }
        public string ord_closer { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public Nullable<System.DateTime> crp_date { get; set; }
        public string mps_yn { get; set; }
        public Nullable<System.DateTime> mps_date { get; set; }
        public string sub_yn { get; set; }
        public Nullable<System.DateTime> sub_date { get; set; }
        public string prod_nbr { get; set; }
        public string price_main_yn { get; set; }
        public string price_sub_yn { get; set; }
        public Nullable<decimal> rough_gross { get; set; }
        public string chn_yn { get; set; }
        public Nullable<System.DateTime> chn_date { get; set; }
        public string chn_turn_out { get; set; }
        public Nullable<System.DateTime> chn_turn_date { get; set; }
        public string pre_nbr { get; set; }
        public string pre_seq { get; set; }
    }
}
