//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordc_bat
    {
        public string site { get; set; }
        public string ord_nbr { get; set; }
        public string ord_seq { get; set; }
        public string cust_po_nbr { get; set; }
        public string season { get; set; }
        public string item_number { get; set; }
        public string hts { get; set; }
        public string pack { get; set; }
        public string sample_class { get; set; }
        public string get_term { get; set; }
        public string transatn_term { get; set; }
        public string last_place { get; set; }
        public string deliver_id { get; set; }
        public string forwarder { get; set; }
        public string quota_id { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> pre_qty { get; set; }
        public Nullable<decimal> real_price { get; set; }
        public Nullable<decimal> add_reduce_item { get; set; }
        public Nullable<decimal> real_qty { get; set; }
        public Nullable<decimal> ord_amt { get; set; }
        public Nullable<decimal> ord_base_amt { get; set; }
        public Nullable<decimal> shp_qty { get; set; }
        public Nullable<decimal> shp_amt { get; set; }
        public Nullable<decimal> rtn_qty { get; set; }
        public Nullable<decimal> rtn_amt { get; set; }
        public Nullable<decimal> wpk_qty { get; set; }
        public Nullable<decimal> shp_time { get; set; }
        public Nullable<decimal> add_export { get; set; }
        public Nullable<decimal> reduce_export { get; set; }
        public Nullable<decimal> cus_brokerage { get; set; }
        public string cus_delivery_range { get; set; }
        public Nullable<System.DateTime> cus_delivery_s { get; set; }
        public Nullable<System.DateTime> cus_delivery_e { get; set; }
        public Nullable<System.DateTime> finish_modify_date { get; set; }
        public Nullable<System.DateTime> qty_modify_date { get; set; }
        public string cancel_yn { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public Nullable<System.DateTime> plan_fin_date { get; set; }
        public Nullable<System.DateTime> finish_date { get; set; }
        public Nullable<System.DateTime> last_date { get; set; }
        public Nullable<System.DateTime> confirm_date { get; set; }
        public string color_price_yn { get; set; }
        public string bat_status { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public string reason { get; set; }
        public string filter_creator { get; set; }
        public string filter_dept { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string po_type { get; set; }
        public Nullable<decimal> est_gross_pcs { get; set; }
        public Nullable<decimal> real_gross_pcs { get; set; }
        public Nullable<decimal> main_cost { get; set; }
        public Nullable<decimal> sub_cost { get; set; }
        public Nullable<System.DateTime> first_shp_date { get; set; }
        public Nullable<System.DateTime> last_shp_date { get; set; }
        public Nullable<decimal> ivc_qty { get; set; }
        public Nullable<decimal> prod_count { get; set; }
        public string sample_yn { get; set; }
        public string acr_cus { get; set; }
        public Nullable<decimal> shp_base_amt { get; set; }
        public Nullable<decimal> rtn_base_amt { get; set; }
        public string contract_record { get; set; }
    }
}
